# Copyright 2025 kangeunchan
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: k8s-resource
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/rkddmscks/k8s-resource.git
        revision: HEAD
        files:
          - path: 'apps/*/config.yaml'
  template:
    metadata:
      name: '{{ .path.basename }}'
      annotations:
        argocd.argoproj.io/sync-wave: '{{ default "10" .syncWave }}'
    spec:
      project: platform
      source:
        repoURL: https://github.com/rkddmscks/k8s-resource.git
        targetRevision: main
        path: 'apps/{{ .path.basename }}'
        helm:
          valueFiles:
            - values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ path.basename }}'
      syncPolicy:
        automated:
          prune: false
          selfHeal: false
          allowEmpty: false
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true
          - RespectIgnoreDifferences=true
