# Copyright 2025 kangeunchan
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

argo-cd:
  global:
    image:
      tag: v3.0.19
    tolerations:
      - key: "workload"
        operator: "Equal"
        value: "platform"
        effect: "NoSchedule"
    podLabels:
      app.kubernetes.io/instance: argocd
    securityContext:
      runAsNonRoot: true
      runAsUser: 999
      fsGroup: 999
  configs:
    cm:
      application.instanceLabelKey: argocd.argoproj.io/instance
      application.resourceTrackingMethod: annotation
    params:
      server.insecure: true
    rbac:
      policy.default: role:readonly
  server:
    service:
      type: LoadBalancer
    extraArgs:
      - --insecure
    ingress:
      enabled: false
  repoServer:
    replicas: 1
  controller:
    replicas: 1
  applicationSet:
    replicas: 1
  redis:
    enabled: true
    podLabels:
      app.kubernetes.io/instance: argocd